name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to google cloud app engine
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create app.yaml file with envs
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
        run: |
          echo $DB_HOST
          envsubst < ./app.yaml.tplt > app.yaml

      - id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}