name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to google cloud app engine
    runs-on: ubuntu-20.04
    steps:
      - name: Create app.yaml file
        run: |
          echo "${APP_YAML_CONTENT}" >> app.yaml
          cat app.yaml
      - id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}