name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to google cloud app engine
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create app.yaml file with envs
        run: |
          printenv
          envsubst < ./app.yaml.tplt > app.yaml
          cat app.yaml

      - id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}